version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.0
    parallelism: 3
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - restore_cache:
          key: yarpc-go
      - run:
          name: 1.8 examples lint test
          command: make ci
          environment:
            - CI_TYPES: examples lint test
            - DOCKER_GO_VERSION: 1.8
      - run:
          name: 1.7 examples cover
          command: make ci
          environment:
            - CI_TYPES: examples cover
            - DOCKER_GO_VERSION: 1.7
      - run:
          name: crossdock
          command: make ci
          environment:
            - CI_TYPES: crossdock
      - save_cache:
          key: yarpc-go
          paths:
            - $HOME/.yarpc-go
