version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.0
    parallelism: 3
    working_directory: /checkout
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
         name: run make ci
         command:
           case $CIRCLE_NODE_INDEX in
           0) DOCKER_GO_VERSION=1.7 CI_TYPES="deps cover" make ci ;;
           1) DOCKER_GO_VERSION=1.8 CI_TYPES="deps lint test examples" make ci ;;
           2) CI_TYPES=crossdock make ci ;;
           esac
